---
- name: RHV infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    #- passwords.yml

  vars:
    #engine_fqdn: ovirt-engine.example.com
    #engine_user: admin@internal
    #engine_cafile: /etc/pki/ovirt-engine/ca.pem

    debug_vm_create: yes
    
    ex_memory: 1GiB
    ex_tag:
      - pgsql
      - httpd
    ex_disk_size: 3GiB
    
    db_vm:
      state: running
      cluster: DemoLab
      template: rhel7vm-template
      memory: 1GiB
      memory_max: 2GiB
      cores: 1
      tag:
        - db
        - dbvm
      disks:
        - size: 2GiB
          name: data
          storage_domain: data-nfs01
          interface: virtio

    vms:
      - name: postgresql-vm-2
        memory: "{{ ex_memory }}"
        profile: "{{ db_vm }}"
        tag: "{{ ex_tag }}"
        db_vm.disks.size: "{{ ex_disk_size }}"


  roles:
    - ovirt.vm-infra
