---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` varibale using ansible-vault
    #- passwords.yml

  vars:
    #engine_fqdn: ovirt-engine.example.com
    #engine_user: admin@internal
    #engine_cafile: /etc/pki/ovirt-engine/ca.pem

    debug_vm_create: yes
    db_vm:
      state: running
      cluster: DemoLab
      template: rhel7vm-template
      memory: 1GiB
      memory_max: 3GiB
      cores: 1
      tag:
        - db
        - dbvm
      disks:
        - size: 1GiB
          name: data
          storage_domain: data-nfs01
          interface: virtio

    vms:
      - name: postgresql-vm-0
        memory: 1GiB
        profile: "{{ db_vm }}"
        tag:
          - pgsql
          - httpd

  roles:
    - ovirt.vm-infra
